#!/usr/bin/env bash
# cron-generator.sh — generate + apply timezone-aware crontab manifest
#
# Reads .agentbloc/team/agent-profiles.yaml triggers[] of type=cron and
# materializes .agentbloc/runtime/crontab.proposed. Then optionally
# stdin-installs into the user's crontab.
#
# Subcommands:
#   generate (default)  Write crontab.proposed from agent-profiles.yaml
#   apply               Generate + backup current crontab + install via stdin
#   diff                Show what apply would change
#   remove              Strip agentbloc-tagged lines from current crontab
#
# Tagging convention:
#   Every emitted cron line ends with `# agentbloc:<scope>:<name>` so we
#   can identify (and uninstall) only what we wrote without disturbing
#   the user's own cron lines.
#
# System lines (always emitted, independent of agent-profiles.yaml):
#   - telegram-poll.sh        every 1 min   (Eng Review F5)
#   - approval-router.sh      every 1 min
#   - escalation-router.sh    every 1 min
#   - activity-feed-merge.sh  daily 00:05 UTC
#
# Per-agent lines (one per trigger of type=cron in agent-profiles.yaml):
#   <schedule> <repo>/scripts/wake.sh <agent-id> cron >> .../cron.log 2>&1
#
# Timezone:
#   TZ= prefix per cron line, taken from agent-profiles.yaml team.timezone
#   if present (schema extension; defaults to UTC). Eng Review F5 calls
#   this out for DST correctness.
#
# Idempotency:
#   `apply` strips existing `# agentbloc:` lines from current crontab,
#   then appends the freshly-generated manifest. Re-running is safe.
#
# Refs: design doc (Wave 3.1, Eng Review F5);
#       references/agent-profile-schema.md (trigger schema).

set -euo pipefail

# ─── Resolve repo root + helpers ─────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
export AGENTBLOC_HOME="${AGENTBLOC_HOME:-$REPO_ROOT}"

# shellcheck source=helpers.sh
. "${SCRIPT_DIR}/helpers.sh"

# ─── Paths ───────────────────────────────────────────────────────────────────
PROFILES_YAML="${AGENTBLOC_HOME}/.agentbloc/team/agent-profiles.yaml"
RUNTIME_DIR="${AGENTBLOC_HOME}/.agentbloc/runtime"
MANIFEST="${RUNTIME_DIR}/crontab.proposed"
LOGS_DIR="${AGENTBLOC_HOME}/.agentbloc/logs"
CRON_LOG="${LOGS_DIR}/cron.log"

mkdir -p "$RUNTIME_DIR" "$LOGS_DIR"

# ─── Tag helpers ─────────────────────────────────────────────────────────────
# Every emitted line ends with `# agentbloc:<scope>:<name>`. uninstall
# greps for `# agentbloc:` to remove what we wrote.
tag_line() {
  local schedule="$1" cmd="$2" scope="$3" name="$4" tz="${5:-UTC}"
  printf 'TZ=%s %s %s >> %s 2>&1 # agentbloc:%s:%s\n' \
    "$tz" "$schedule" "$cmd" "$CRON_LOG" "$scope" "$name"
}

# ─── Load timezone from agent-profiles.yaml (if present) ────────────────────
load_timezone() {
  if [ ! -f "$PROFILES_YAML" ]; then
    echo "UTC"
    return
  fi
  if ! command -v python3 >/dev/null 2>&1; then
    echo "UTC"
    return
  fi
  python3 - <<'PY' "$PROFILES_YAML"
import sys, yaml
try:
    with open(sys.argv[1]) as f:
        data = yaml.safe_load(f) or {}
    tz = (data.get("team") or {}).get("timezone") or "UTC"
    print(tz)
except Exception:
    print("UTC")
PY
}

# ─── Generate manifest ───────────────────────────────────────────────────────
cmd_generate() {
  local tz
  tz=$(load_timezone)

  {
    echo "# AgentBloc-generated crontab manifest"
    echo "# Source: ${PROFILES_YAML#${AGENTBLOC_HOME}/}"
    echo "# Timezone: ${tz}"
    echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# DO NOT EDIT — regenerated by scripts/cron-generator.sh"
    echo "# Lines tagged 'agentbloc:' are managed; remove via 'cron-generator.sh remove'"
    echo ""
    echo "# ─── system lines (telegram bridge + housekeeping) ───────────────"
    tag_line "* * * * *"     "${SCRIPT_DIR}/telegram-poll.sh"          system telegram-poll      "$tz"
    tag_line "* * * * *"     "${SCRIPT_DIR}/approval-router.sh"        system approval-router    "$tz"
    tag_line "* * * * *"     "${SCRIPT_DIR}/escalation-router.sh"      system escalation-router  "$tz"
    tag_line "5 0 * * *"     "${SCRIPT_DIR}/activity-feed-merge.sh"    system activity-feed-merge "$tz"
    echo ""
    echo "# ─── per-agent wake lines ────────────────────────────────────────"
  } > "$MANIFEST"

  if [ ! -f "$PROFILES_YAML" ]; then
    {
      echo "# (no agent-profiles.yaml found at ${PROFILES_YAML#${AGENTBLOC_HOME}/} —"
      echo "#  emit per-agent lines on next regeneration after Wave 6 demo team)"
    } >> "$MANIFEST"
    echo "cron-generator: agent-profiles.yaml not found; manifest contains system lines only" >&2
    echo "  Wrote: ${MANIFEST}"
    return 0
  fi

  if ! command -v python3 >/dev/null 2>&1; then
    echo "[AB-009] python3 not found in PATH (cron-generator.sh requires python3 + PyYAML)" >&2
    return 1
  fi

  # Extract per-agent cron triggers via python3 + PyYAML. Output one
  # line per (agent-id, schedule) tuple, tab-separated.
  AGENT_ROWS=$(python3 - <<'PY' "$PROFILES_YAML"
import sys, yaml
try:
    with open(sys.argv[1]) as f:
        data = yaml.safe_load(f) or {}
except Exception as e:
    sys.stderr.write(f"cron-generator: failed to parse {sys.argv[1]}: {e}\n")
    sys.exit(1)

agents = data.get("agents") or []
for agent in agents:
    aid = agent.get("id")
    if not aid:
        continue
    for trig in (agent.get("triggers") or []):
        if (trig or {}).get("type") != "cron":
            continue
        schedule = trig.get("schedule")
        if not schedule:
            continue
        print(f"{aid}\t{schedule}")
PY
)

  if [ -z "$AGENT_ROWS" ]; then
    echo "# (no cron triggers in agent-profiles.yaml)" >> "$MANIFEST"
  else
    while IFS=$'\t' read -r agent_id schedule; do
      [ -z "$agent_id" ] && continue
      tag_line "$schedule" \
        "${SCRIPT_DIR}/wake.sh ${agent_id} cron" \
        agent "$agent_id" "$tz" >> "$MANIFEST"
    done <<< "$AGENT_ROWS"
  fi

  echo "cron-generator: manifest written"
  echo "  ${MANIFEST}"
}

# ─── Strip existing agentbloc-tagged lines from a stream ─────────────────────
strip_agentbloc_lines() {
  # Filter input stream, removing lines containing "# agentbloc:" tag.
  grep -v '# agentbloc:' || true
}

# ─── Apply (idempotent stdin install) ────────────────────────────────────────
cmd_apply() {
  cmd_generate

  if ! command -v crontab >/dev/null 2>&1; then
    echo "cron-generator: crontab(1) not found in PATH" >&2
    echo "  Fix: set AGENTBLOC_NO_CRON=1 and use ./scripts/loop.sh instead" >&2
    return 1
  fi

  # Snapshot current crontab (or empty if user has none — first crontab -l
  # exits non-zero on some macOS configs when no crontab exists).
  CURRENT_CRONTAB=$(crontab -l 2>/dev/null || true)

  # Backup before mutation. Backup goes under runtime/, not committed.
  BACKUP="${RUNTIME_DIR}/crontab.backup.$(date -u +%Y%m%dT%H%M%SZ)"
  printf '%s\n' "$CURRENT_CRONTAB" > "$BACKUP"

  # Build merged crontab: filtered-existing + our manifest.
  MERGED=$(printf '%s\n' "$CURRENT_CRONTAB" | strip_agentbloc_lines)
  MERGED="$(printf '%s\n%s\n' "$MERGED" "$(cat "$MANIFEST")")"

  # Detect EPERM scenario before we try (AB-004): on macOS Sonoma+ with
  # FDA off, `crontab -` returns 1 with "Operation not permitted".
  if ! printf '%s' "$MERGED" | crontab - 2>/tmp/cron-err.$$; then
    echo "[AB-004] crontab install failed" >&2
    sed 's/^/  /' /tmp/cron-err.$$ >&2 || true
    rm -f /tmp/cron-err.$$
    echo "  Fix: on macOS, grant Full Disk Access to your terminal app, OR" >&2
    echo "       set AGENTBLOC_NO_CRON=1 and run ./scripts/loop.sh instead" >&2
    echo "  Backup of prior crontab: ${BACKUP}" >&2
    return 1
  fi
  rm -f /tmp/cron-err.$$

  echo "cron-generator: applied"
  echo "  manifest: ${MANIFEST}"
  echo "  backup:   ${BACKUP}"
}

# ─── Diff ────────────────────────────────────────────────────────────────────
cmd_diff() {
  cmd_generate >/dev/null

  CURRENT=$(crontab -l 2>/dev/null || true)
  AB_LINES_NOW=$(printf '%s\n' "$CURRENT" | grep '# agentbloc:' || true)
  PROPOSED=$(grep '# agentbloc:' "$MANIFEST" || true)

  if [ "$AB_LINES_NOW" = "$PROPOSED" ]; then
    echo "cron-generator: no changes (already in sync)"
    return 0
  fi

  echo "--- current agentbloc lines ---"
  printf '%s\n' "$AB_LINES_NOW"
  echo "--- proposed agentbloc lines ---"
  printf '%s\n' "$PROPOSED"
}

# ─── Remove ──────────────────────────────────────────────────────────────────
cmd_remove() {
  if ! command -v crontab >/dev/null 2>&1; then
    echo "cron-generator: crontab(1) not found in PATH" >&2
    return 1
  fi

  CURRENT=$(crontab -l 2>/dev/null || true)
  if [ -z "$CURRENT" ]; then
    echo "cron-generator: no crontab to clean"
    return 0
  fi

  BACKUP="${RUNTIME_DIR}/crontab.backup.$(date -u +%Y%m%dT%H%M%SZ)"
  printf '%s\n' "$CURRENT" > "$BACKUP"

  CLEANED=$(printf '%s\n' "$CURRENT" | strip_agentbloc_lines)

  if [ -z "$CLEANED" ] || [ "$CLEANED" = "$(printf '\n')" ]; then
    crontab -r 2>/dev/null || true
    echo "cron-generator: removed all agentbloc lines (crontab now empty; cleared)"
  else
    printf '%s\n' "$CLEANED" | crontab -
    echo "cron-generator: removed agentbloc lines"
  fi
  echo "  backup: ${BACKUP}"
}

# ─── Subcommand dispatch ─────────────────────────────────────────────────────
SUBCMD="${1:-generate}"
case "$SUBCMD" in
  generate) cmd_generate ;;
  apply)    cmd_apply ;;
  diff)     cmd_diff ;;
  remove)   cmd_remove ;;
  --help|-h)
    cat <<EOF
cron-generator.sh — manage AgentBloc cron lines

Usage: cron-generator.sh [generate | apply | diff | remove]

  generate   Write .agentbloc/runtime/crontab.proposed from
             .agentbloc/team/agent-profiles.yaml. (default)
  apply      generate + idempotent install via 'crontab -' stdin.
             Existing # agentbloc: lines are replaced; user's own
             cron lines are preserved.
  diff       Show pending changes vs the current crontab.
  remove     Strip all # agentbloc: lines from the current crontab.

Tunables (.env):
  AGENTBLOC_HOME (default: repo root)

System cron lines (always emitted):
  telegram-poll, approval-router, escalation-router  every 1 min
  activity-feed-merge                                daily 00:05

Per-agent cron lines emitted from agent-profiles.yaml:
  triggers[] of type=cron with a schedule field.

Refs: agent-profile-schema.md, design doc Wave 3.1, Eng Review F5.
EOF
    ;;
  *)
    echo "cron-generator.sh: unknown subcommand '${SUBCMD}'" >&2
    echo "Try: cron-generator.sh --help" >&2
    exit 2
    ;;
esac
